name: IBM Cloud Auto Restart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download And Install
      run: curl -sL https://ibm.biz/idt-installer | bash
      
    - name: Login IBM Cloud
      run: |
        ibmcloud login <<EOF
        ${{ secrets.LOGIN_NAME }}
        ${{ secrets.MIMA }}
        7
        no
        EOF
    - name: Do My Jobs
      run: |
        ibmcloud cf l -a https://api.US-SOUTH.cf.cloud.ibm.com login -u ${{ secrets.LOGIN_NAME }} -p ${{ secrets.MIMA }}
        ibmcloud cf install
        ibmcloud cf restart deardct
