name: IBM Cloud Auto Restart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 12 * * FRI'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download And Install
      run: curl -sL https://ibm.biz/idt-installer | bash
      
    - name: Login IBM Cloud
      run: |
        ibmcloud login <<EOF
        ${{LOGIN_NAME}}
        ${{MiMA}}
        7
        no
        EOF
    - name: Do My Jobs
      run: |
        ibmcloud target -g 3fad07e49caf4759bd5e0fae3dae6291
        ibmcloud target --cf
        ibmcloud cf install
        ibmcloud cf restart deardct
